version: '3.2'
services:
  mysql:
    image: mysql
    container_name: mysql
    build:
      dockerfile: Dockerfile-mysql
      context: .
    ports:
      - "3306:3306"
  tcpproxy:
    image: tcpproxy
    container_name: tcpproxy
    build:
      dockerfile: Dockerfile-tcpproxy
      context: .
    depends_on:
      - mysql
    ports:
      - "3307:3307"
    tty: true
    privileged: true
  kimo:
    image: kimo
    container_name: kimo
    build:
      dockerfile: Dockerfile-kimo
      context: .
    depends_on:
      - mysql
    tty: true
  kimo-daemon:
    image: kimo-daemon
    build:
      dockerfile: Dockerfile-kimo-daemon
      context: .
    ports:
      - "3333"
    depends_on:
      - tcpproxy
    tty: true
  kimo-server:
    image: kimo-server
    container_name: kimo-server
    entrypoint: /go/src/kimo/kimo -c /etc/kimo.toml server
    ports:
      - "3322:3322"
    build:
      dockerfile: Dockerfile-kimo
      context: .
    tty: true
