version: '3.2'
services:
  mysql:
    image: mysql
    container_name: mysql
    build:
      dockerfile: Dockerfile-mysql
      context: .
    ports:
      - "3306:3306"
  tcpproxy:
    image: tcpproxy
    container_name: tcpproxy
    build:
      dockerfile: Dockerfile-tcpproxy
      context: .
    depends_on:
      - mysql
    ports:
      - "3307:3307"
    tty: true
    privileged: true
  kimo:
    image: kimo
    container_name: kimo
    build:
      dockerfile: Dockerfile-kimo
      context: .
    depends_on:
      - mysql
    tty: true
  kimo-server:
    image: kimo-server
    container_name: kimo-server
    build:
      dockerfile: Dockerfile-kimo-server
      context: .
    ports:
      - "3333:3333"
    depends_on:
      - kimo
    tty: true
  kimo-client:
    image: kimo-client
    container_name: kimo-client
    build:
      dockerfile: Dockerfile-kimo
      context: .
    depends_on:
      - kimo-server
    tty: true
