name: build
on: release
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check
        run: |
          ./goreleaser check
      -
        name: GoReleaser
        run: |
          ./goreleaser build
